spring:
  datasource:
    url: jdbc:h2:file:./h2db/vegetable
    driverClassName: org.h2.Driver
    username: sa
    password: pass
    
  jpa: 
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: 
      ddl-auto: create-drop

  h2: 
    console: 
      enabled: true
      path: /h2-ui